Repository mokumoku-lovers/moku-moku-auth, pull requests merged in 2021-12, with the labels that each got.

#41 Feature/login user api/39
  app/application.go
  domain/access_token/access_token.go
  domain/access_token/service.go
  go.mod
  go.sum
  http/http_access_token.go
  repository/rest/users_repository.go
Labels: enhancement, Task

#43 Docs/swagger documentation/42
  app/application.go
  go.mod
  go.sum
  http_at/http_access_token.go
  swagger.yml
Labels: documentation, Task

#44 Dev
  app/application.go
  clients/cassandra/cassandra_db.go
  domain/access_token/access_token.go
  domain/access_token/access_token_test.go
  domain/access_token/service.go
  domain/users/user.go
  go.mod
  go.sum
  http_at/http_access_token.go
  main.go
  repository/db/db_repository.go
  repository/rest/users_repository.go
  swagger.yml
  utils/crypto_utils/crypto_utils.go
  utils/errors/errors.go
Labels: documentation, enhancement, DB

#46 Feat/oauth schema/45
  repository/db/oauth_db.cql
Labels: Task, DB

#47 Database setup
  repository/db/oauth_db.cql
Labels: documentation, DB
